name: Tag deploy to S3
on:
  push:
    branches: 
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out to the latest tag
        uses: actions/checkout@v2

      - name: Npm Install
        run: |
          npm install
          npm run-script build
        # env: 
        #   NODE_ENV: production
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: us-east-2
      
      - name: Copy dist to the s3
        run: aws s3 sync ./build s3://my-xiaowei-hosted-content --delete

