name: Tag deploy to S3
on:
  push:
    branches: 
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          # role-to-assume: arn:aws:iam::732504503399:user/test
          aws-access-key-id: AKIA2VDFLWRTZXALFY5B
          aws-secret-access-key: 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
          aws-region: us-east-2
        run: |
          aws s3 sync . s3://my-xiaowei-hosted-content

